version: '3'
services:
  mongodb:
    image: mongo
    logging:
      driver: none
    networks:
      - demo
    ports:
      - '27017:27017'

  core:
    image: node:10
    working_dir: /usr/src/app
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8081:8081'
    volumes:
      - './core:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm install && npm run docker:dev"

  policy:
    image: node:10
    working_dir: /usr/src/app
    depends_on:
      - mongodb
    networks:
      - demo
    ports:
      - '8082:8082'
    volumes:
      - './modules/policy:/usr/src/app'
      - '/root/.npm'
    command: bash -c "npm install && npm run docker:dev"
networks:
  demo:
    driver: bridge
